### ISSUE TITLE
Rename package from "client"

### ISSUE THREAD

**Issue by taion** [avadev/AvaTax-REST-V2-Python-SDK#38]
It's a little confusing that the package is just `client`. This seems potentially prone to causing name collisions, and also hurts readability of code using this library.

It seems like it would be better if the import instead looked like e.g.:

```python
from avalara import AvataxClient
```

**Comment by afreepenguin** [comment]
This was merged... should be in the docs under whatever version it was merged in for. Docs are a bit confusing given that.

**Comment by afreepenguin** [comment]
Should leave the issue open until the docs are updated?

**Comment by taion** [comment]
@afreepenguin I figured it would be less confusing to close this out given that #85 is open as well. I opened https://github.com/avadev/AvaTax-REST-V2-Python-SDK/pull/86 to fix the docs.
